/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */
import type {
  ChatEventCatalog,
  ChatIn,
  RecommendIn
} from './model';

/**
 * 리브니스 + DB(age·vector 확장) 가용성 체크 (이슈 02).
 * @summary Health
 */
export type appsCoreApiHealthResponse200 = {
  data: void
  status: 200
}
    
export type appsCoreApiHealthResponseSuccess = (appsCoreApiHealthResponse200) & {
  headers: Headers;
};
;

export type appsCoreApiHealthResponse = (appsCoreApiHealthResponseSuccess)

export const getAppsCoreApiHealthUrl = () => {


  

  return `/health`
}

export const appsCoreApiHealth = async ( options?: RequestInit): Promise<appsCoreApiHealthResponse> => {
  
  const res = await fetch(getAppsCoreApiHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: appsCoreApiHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appsCoreApiHealthResponse
}



/**
 * @summary Recommend Endpoint
 */
export type appsAgentApiRecommendEndpointResponse200 = {
  data: void
  status: 200
}
    
export type appsAgentApiRecommendEndpointResponseSuccess = (appsAgentApiRecommendEndpointResponse200) & {
  headers: Headers;
};
;

export type appsAgentApiRecommendEndpointResponse = (appsAgentApiRecommendEndpointResponseSuccess)

export const getAppsAgentApiRecommendEndpointUrl = () => {


  

  return `/recommend`
}

export const appsAgentApiRecommendEndpoint = async (recommendIn: RecommendIn, options?: RequestInit): Promise<appsAgentApiRecommendEndpointResponse> => {
  
  const res = await fetch(getAppsAgentApiRecommendEndpointUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      recommendIn,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: appsAgentApiRecommendEndpointResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appsAgentApiRecommendEndpointResponse
}



/**
 * 코드젠 전용: POST /chat 요청 본문(ChatIn)과 SSE 이벤트 페이로드 타입을 노출한다.

실제 대화는 스트리밍 뷰 POST /chat이 처리한다(SSE, text/event-stream).
 * @summary Chat Event Schema
 */
export type appsAgentApiChatEventSchemaResponse200 = {
  data: ChatEventCatalog
  status: 200
}
    
export type appsAgentApiChatEventSchemaResponseSuccess = (appsAgentApiChatEventSchemaResponse200) & {
  headers: Headers;
};
;

export type appsAgentApiChatEventSchemaResponse = (appsAgentApiChatEventSchemaResponseSuccess)

export const getAppsAgentApiChatEventSchemaUrl = () => {


  

  return `/chat/schema`
}

export const appsAgentApiChatEventSchema = async (chatIn: ChatIn, options?: RequestInit): Promise<appsAgentApiChatEventSchemaResponse> => {
  
  const res = await fetch(getAppsAgentApiChatEventSchemaUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      chatIn,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: appsAgentApiChatEventSchemaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appsAgentApiChatEventSchemaResponse
}
