/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */
import type { TokenData } from './tokenData';
import type { RecommendationData } from './recommendationData';
import type { ClarificationData } from './clarificationData';
import type { StatusData } from './statusData';
import type { ErrorData } from './errorData';
import type { SuggestionsData } from './suggestionsData';

/**
 * SSE 이벤트 페이로드 카탈로그(코드젠 전용).
 */
export interface ChatEventCatalog {
  token: TokenData;
  recommendation: RecommendationData;
  clarification: ClarificationData;
  status: StatusData;
  error: ErrorData;
  suggestions: SuggestionsData;
}
