/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */
import type { HistoryMessage } from './historyMessage';

/**
 * POST /chat 요청 본문.
 */
export interface ChatIn {
  query: string;
  history?: HistoryMessage[];
}
