/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */

/**
 * event: clarification — 되묻기 문구.
 */
export interface ClarificationData {
  question: string;
}
