/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */

/**
 * event: error — 스트림 내 오류.
 */
export interface ErrorData {
  message: string;
}
