/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */

export interface GroundingItem {
  name: string;
  value: string;
  provenance: string;
}
