/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 무상태 멀티턴 히스토리 한 줄. role: user | assistant.
 */
export interface HistoryMessage {
  role: string;
  content: string;
}
