/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */

/**
 * event: notice — 품절 상품 구매요청 안내(프롬프트 + 상품별 요청 버튼).
 */
export interface NoticeData {
  prompt?: string;
  items?: string[];
}
