/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */

/**
 * event: notice — 품절 등 안내(근거와 분리된 별도 박스로 표시).
 */
export interface NoticeData {
  message: string;
}
