/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */
import type { ProductCardImageUrl } from './productCardImageUrl';
import type { ProductCardPriceMin } from './productCardPriceMin';
import type { ProductCardPriceMax } from './productCardPriceMax';
import type { GroundingItem } from './groundingItem';

export interface ProductCard {
  source_id: string;
  name: string;
  url: string;
  image_url?: ProductCardImageUrl;
  price_min?: ProductCardPriceMin;
  price_max?: ProductCardPriceMax;
  grounding?: GroundingItem[];
}
