/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */
import type { ProductCard } from './productCard';

/**
 * event: recommendation — 결정적으로 부착된 상품 카드.
 */
export interface RecommendationData {
  products?: ProductCard[];
}
