/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */

/**
 * event: status — 도구 호출 진행 상태(첫 토큰 전 전환형 표시).
 */
export interface StatusData {
  label: string;
}
