/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */

/**
 * event: suggestions — 응답 뒤 후속 검색어 칩(클릭해 대화 지속).
 */
export interface SuggestionsData {
  suggestions?: string[];
}
