/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kolab KG Chat API
 * OpenAPI spec version: 0.1.0
 */

/**
 * event: token — 추천 근거 토큰 조각.
 */
export interface TokenData {
  content: string;
}
